// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: InviationService.proto

package proto

import (
	common "auth-haven/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of common/Tokens.proto.

type Tokens = common.Tokens
type InviteToken = common.InviteToken

type InviteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RoleId        int32                  `protobuf:"varint,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // maps to roles table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteEmployeeRequest) Reset() {
	*x = InviteEmployeeRequest{}
	mi := &file_InviationService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteEmployeeRequest) ProtoMessage() {}

func (x *InviteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InviationService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*InviteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_InviationService_proto_rawDescGZIP(), []int{0}
}

func (x *InviteEmployeeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InviteEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteEmployeeRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type AcceptInviteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InvitationToken string                 `protobuf:"bytes,1,opt,name=invitation_token,json=invitationToken,proto3" json:"invitation_token,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName        string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptInviteRequest) Reset() {
	*x = AcceptInviteRequest{}
	mi := &file_InviationService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteRequest) ProtoMessage() {}

func (x *AcceptInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InviationService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteRequest.ProtoReflect.Descriptor instead.
func (*AcceptInviteRequest) Descriptor() ([]byte, []int) {
	return file_InviationService_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptInviteRequest) GetInvitationToken() string {
	if x != nil {
		return x.InvitationToken
	}
	return ""
}

func (x *AcceptInviteRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AcceptInviteRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_InviationService_proto protoreflect.FileDescriptor

const file_InviationService_proto_rawDesc = "" +
	"\n" +
	"\x16InviationService.proto\x12\x04auth\x1a\x13common/Tokens.proto\"c\n" +
	"\x15InviteEmployeeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\x05R\x06roleId\"y\n" +
	"\x13AcceptInviteRequest\x12)\n" +
	"\x10invitation_token\x18\x01 \x01(\tR\x0finvitationToken\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName2\x8e\x01\n" +
	"\rInviteService\x12B\n" +
	"\x0eInviteEmployee\x12\x1b.auth.InviteEmployeeRequest\x1a\x13.common.InviteToken\x129\n" +
	"\fAcceptInvite\x12\x19.auth.AcceptInviteRequest\x1a\x0e.common.TokensB\x16Z\x14auth-haven/pkg/protoP\x00b\x06proto3"

var (
	file_InviationService_proto_rawDescOnce sync.Once
	file_InviationService_proto_rawDescData []byte
)

func file_InviationService_proto_rawDescGZIP() []byte {
	file_InviationService_proto_rawDescOnce.Do(func() {
		file_InviationService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_InviationService_proto_rawDesc), len(file_InviationService_proto_rawDesc)))
	})
	return file_InviationService_proto_rawDescData
}

var file_InviationService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_InviationService_proto_goTypes = []any{
	(*InviteEmployeeRequest)(nil), // 0: auth.InviteEmployeeRequest
	(*AcceptInviteRequest)(nil),   // 1: auth.AcceptInviteRequest
	(*common.InviteToken)(nil),    // 2: common.InviteToken
	(*common.Tokens)(nil),         // 3: common.Tokens
}
var file_InviationService_proto_depIdxs = []int32{
	0, // 0: auth.InviteService.InviteEmployee:input_type -> auth.InviteEmployeeRequest
	1, // 1: auth.InviteService.AcceptInvite:input_type -> auth.AcceptInviteRequest
	2, // 2: auth.InviteService.InviteEmployee:output_type -> common.InviteToken
	3, // 3: auth.InviteService.AcceptInvite:output_type -> common.Tokens
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_InviationService_proto_init() }
func file_InviationService_proto_init() {
	if File_InviationService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_InviationService_proto_rawDesc), len(file_InviationService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_InviationService_proto_goTypes,
		DependencyIndexes: file_InviationService_proto_depIdxs,
		MessageInfos:      file_InviationService_proto_msgTypes,
	}.Build()
	File_InviationService_proto = out.File
	file_InviationService_proto_goTypes = nil
	file_InviationService_proto_depIdxs = nil
}
